# Generated by Django 3.0.3 on 2020-10-06 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='Video',
            new_name='video',
        ),
    ]
