# Generated by Django 3.0.3 on 2020-10-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20201006_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.FileField(null=True, upload_to='images/', verbose_name='Image File'),
        ),
    ]
