# Generated by Django 3.0.3 on 2020-10-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_video_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
